#!/bin/bash
set -e

# BSVS Installer - Integrates with existing BookStack installations
# Usage: ./install.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="${SCRIPT_DIR}/production"
COMPOSE_FILE="${CONFIG_DIR}/docker-compose.yml"
ENV_FILE="${CONFIG_DIR}/.env"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_banner() {
    echo -e "${BLUE}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║           BookStack Video Service (BSVS) Installer           ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_step() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

check_dependencies() {
    echo -e "\n${BLUE}Checking dependencies...${NC}"

    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed. Please install Docker first."
        exit 1
    fi
    print_step "Docker found"

    if ! command -v docker compose &> /dev/null && ! command -v docker-compose &> /dev/null; then
        print_error "Docker Compose is not installed. Please install Docker Compose first."
        exit 1
    fi
    print_step "Docker Compose found"
}

get_user_input() {
    echo -e "\n${BLUE}Configuration${NC}"
    echo "Please provide the following information:"
    echo ""

    # BSVS Host
    read -p "BSVS hostname/IP (where BSVS will be accessible) [localhost]: " BSVS_HOST
    BSVS_HOST="${BSVS_HOST:-localhost}"

    # BSVS Port
    read -p "BSVS port [8080]: " BSVS_PORT
    BSVS_PORT="${BSVS_PORT:-8080}"

    # BookStack URL
    read -p "BookStack URL (e.g., https://wiki.example.com): " BOOKSTACK_URL
    if [ -z "$BOOKSTACK_URL" ]; then
        print_error "BookStack URL is required"
        exit 1
    fi

    # Storage path
    read -p "Video storage path [./data/videos]: " STORAGE_PATH
    STORAGE_PATH="${STORAGE_PATH:-./data/videos}"

    # Generate secret key
    SECRET_KEY=$(openssl rand -hex 32)

    # Determine BSVS URL
    if [ "$BSVS_HOST" = "localhost" ] || [ "$BSVS_HOST" = "127.0.0.1" ]; then
        BSVS_URL="http://${BSVS_HOST}:${BSVS_PORT}"
    else
        read -p "Use HTTPS for BSVS? [y/N]: " USE_HTTPS
        if [[ "$USE_HTTPS" =~ ^[Yy]$ ]]; then
            BSVS_URL="https://${BSVS_HOST}"
        else
            BSVS_URL="http://${BSVS_HOST}:${BSVS_PORT}"
        fi
    fi
}

create_config() {
    echo -e "\n${BLUE}Creating configuration...${NC}"

    # Create production directory
    mkdir -p "${CONFIG_DIR}"
    mkdir -p "${STORAGE_PATH}"

    # Create .env file
    cat > "${ENV_FILE}" <<EOF
# BSVS Configuration
# Generated by install.sh on $(date)

# Core Settings
BSVS_PORT=${BSVS_PORT}
BSVS_SECRET_KEY=${SECRET_KEY}
BSVS_DEBUG=false

# Database (SQLite by default, change to PostgreSQL for production)
BSVS_DATABASE_URL=sqlite+aiosqlite:////data/bsvs.db

# Storage
BSVS_STORAGE_PATH=/data/videos

# Transcoding
BSVS_TRANSCODE_PRESETS=1080p,720p,480p
BSVS_MAX_UPLOAD_SIZE_MB=2048

# BookStack Integration
BSVS_BOOKSTACK_URL=${BOOKSTACK_URL}
# Uncomment and set these for API-based auth:
# BSVS_BOOKSTACK_TOKEN_ID=your_token_id
# BSVS_BOOKSTACK_TOKEN_SECRET=your_token_secret
EOF

    print_step "Created ${ENV_FILE}"

    # Create docker-compose.yml
    cat > "${COMPOSE_FILE}" <<EOF
version: '3.8'

services:
  bsvs-api:
    image: ghcr.io/helo-3301/bookstack-video-service:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bsvs-api
    ports:
      - "${BSVS_PORT}:8080"
    env_file:
      - .env
    volumes:
      - bsvs-data:/data
    depends_on:
      - bsvs-redis
    restart: unless-stopped

  bsvs-worker:
    image: ghcr.io/helo-3301/bookstack-video-service:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bsvs-worker
    command: celery -A bsvs.worker.celery_app worker --loglevel=info -Q default,transcode
    env_file:
      - .env
    environment:
      - BSVS_DATABASE_URL=sqlite:////data/bsvs.db
      - BSVS_REDIS_URL=redis://bsvs-redis:6379/0
    volumes:
      - bsvs-data:/data
    depends_on:
      - bsvs-redis
    restart: unless-stopped

  bsvs-redis:
    image: redis:7-alpine
    container_name: bsvs-redis
    volumes:
      - bsvs-redis-data:/data
    restart: unless-stopped

volumes:
  bsvs-data:
  bsvs-redis-data:
EOF

    print_step "Created ${COMPOSE_FILE}"
}

generate_bookstack_snippet() {
    # Generate the JavaScript snippet for BookStack
    PLUGIN_SNIPPET="<!-- BSVS Video Integration -->
<script>window.BSVS_URL = '${BSVS_URL}';</script>
<script src=\"${BSVS_URL}/static/js/bookstack-plugin.js\"></script>"

    echo "$PLUGIN_SNIPPET"
}

print_bookstack_instructions() {
    echo -e "\n${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║              BookStack Configuration Required                ║${NC}"
    echo -e "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}"

    echo -e "\n${YELLOW}Step 1: Update BookStack Environment${NC}"
    echo "Add these lines to your BookStack .env file:"
    echo ""
    echo -e "${GREEN}ALLOWED_IFRAME_HOSTS=\"${BSVS_URL}\"${NC}"
    echo -e "${GREEN}ALLOWED_IFRAME_SOURCES=\"${BSVS_URL}\"${NC}"
    echo ""

    echo -e "${YELLOW}Step 2: Clear BookStack Cache${NC}"
    echo "If using Docker:"
    echo -e "${GREEN}docker exec <bookstack-container> php /app/www/artisan config:clear${NC}"
    echo -e "${GREEN}docker exec <bookstack-container> php /app/www/artisan cache:clear${NC}"
    echo ""
    echo "If installed directly:"
    echo -e "${GREEN}cd /path/to/bookstack && php artisan config:clear && php artisan cache:clear${NC}"
    echo ""

    echo -e "${YELLOW}Step 3: Add BSVS Plugin to BookStack${NC}"
    echo "Go to: BookStack Admin → Settings → Customization"
    echo "Paste this into 'Custom HTML Head Content':"
    echo ""
    echo -e "${GREEN}$(generate_bookstack_snippet)${NC}"
    echo ""

    # Save snippet to file for easy copy
    generate_bookstack_snippet > "${CONFIG_DIR}/bookstack-snippet.html"
    print_step "Saved snippet to ${CONFIG_DIR}/bookstack-snippet.html"
}

start_services() {
    echo -e "\n${BLUE}Starting BSVS services...${NC}"

    cd "${CONFIG_DIR}"

    # Check if we need to build or can pull
    read -p "Build from source or pull image? [build/pull]: " BUILD_CHOICE

    if [ "$BUILD_CHOICE" = "pull" ]; then
        docker compose pull 2>/dev/null || docker-compose pull
        docker compose up -d 2>/dev/null || docker-compose up -d
    else
        docker compose up -d --build 2>/dev/null || docker-compose up -d --build
    fi

    print_step "BSVS services started"

    # Wait for API to be ready
    echo "Waiting for API to be ready..."
    for i in {1..30}; do
        if curl -s "http://localhost:${BSVS_PORT}/health" > /dev/null 2>&1; then
            print_step "API is ready"
            break
        fi
        sleep 1
    done
}

print_summary() {
    echo -e "\n${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║                    Installation Complete!                     ║${NC}"
    echo -e "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "BSVS URL:        ${GREEN}${BSVS_URL}${NC}"
    echo -e "Upload UI:       ${GREEN}${BSVS_URL}/${NC}"
    echo -e "Admin UI:        ${GREEN}${BSVS_URL}/admin${NC}"
    echo -e "Health Check:    ${GREEN}${BSVS_URL}/health${NC}"
    echo ""
    echo -e "Config files:    ${CONFIG_DIR}/"
    echo -e "Video storage:   ${STORAGE_PATH}"
    echo ""
    echo -e "${YELLOW}Don't forget to configure BookStack as shown above!${NC}"
}

# Main installation flow
main() {
    print_banner
    check_dependencies
    get_user_input
    create_config

    read -p "Start BSVS services now? [Y/n]: " START_NOW
    if [[ ! "$START_NOW" =~ ^[Nn]$ ]]; then
        start_services
    fi

    print_bookstack_instructions
    print_summary
}

main "$@"
